### ISSUE TITLE
How do I configure sasl jaas authentication?

### ISSUE THREAD

**Issue by gabrieljones** [Consdata/kouncil#184]
https://docs.confluent.io/platform/current/kafka/authentication_sasl/index.html#jaas-configurations

**Comment by ynleborg** [comment]
@gabrieljones  Currently Kouncil doesn't support this feature, we are working on implementing this.

**Comment by rahulpandey8920** [comment]
Are there any environment variables which can be passed for the username and password in the docker run command ?
```
docker run -d -p 8070:8080 -e bootstrapServers="localhost:9092" consdata/kouncil:latest
```

**Comment by ynleborg** [comment]
With the newest release (ver 1.5) all topics around authentication and TLS are implemented. Feel free to raise a question if anything that you need is missing.
