### ISSUE TITLE
Adding an option to hide internal confluent topics _confluent-*

### ISSUE THREAD

**Issue by iamvibhorsingh** [Consdata/kouncil#185]
Users who use confluent's kafka have a lot of internal confluent topics in brokers and they all start with "_confluent-" so it'd be nice if there was a simple toggle to hide all of them in the topic list page as one has to scroll past them everytime the topic page is loaded (they start with a special character so they appear before all conventionally named topics) which is a bit frustrating. Thanks!

**Comment by ynleborg** [comment]
@iamvibhorsingh this is a great idea. We can introduce pattern for topic names to be hidden in the configuration file. I will put it on our roadmap. Stay tuned ;)

**Comment by ynleborg** [comment]
@iamvibhorsingh You can now exclude topics using regex list. Just set 
`-Dkouncil.topics.exclude-regex-patterns=__.*,_confluent-.*`
