### ISSUE TITLE
Support for schema registry or AVRO records?

### ISSUE THREAD

**Issue by iamvibhorsingh** [Consdata/kouncil#186]
Does the tool support avro records because currently it returns null when i try to view the value of avro records

If not, is that something you guys plan to introduce in the future?

Thanks!

**Comment by ynleborg** [comment]
@iamvibhorsingh Currently we are focused on plain text messages containing JSON. But both Avro and Protobuf will be supported in the near future. Stay tuned!

**Comment by ynleborg** [comment]
@iamvibhorsingh SchemaRegistry and Protobuff are supported since 1.2 
AVRO is next on the roadmap ;)

**Comment by ynleborg** [comment]
Both Avro and Protobuf are supported since 1.3
