### ISSUE TITLE
Cannot connect with brokers if Docker Network Bridge is configured

### ISSUE THREAD

**Issue by SENIAN** [Consdata/kouncil#192]
**[main] c.c.kouncil.config.KouncilConfiguration  :** 
KouncilConfiguration(initialBootstrapServers=[172.23.0.20:9092, 172.23.0.21:9094, 172.23.0.22:9096], 
clusters=
**[ClusterConfig(name=kafka-n, jmxPort=null, jmxUser=null, jmxPassword=null,**
brokers=
BrokerConfig(host=172.23.0.20, port=9092, jmxPort=null, jmxUser=null, jmxPassword=null), 
BrokerConfig(host=172.23.0.21, port=9093, jmxPort=null, jmxUser=null, jmxPassword=null), 
BrokerConfig(host=172.23.0.22, port=9094, jmxPort=null, jmxUser=null, jmxPassword=null)])], 

**clusterConfig={kafka_ndsal=ClusterConfig(name=kafka-n, jmxPort=null, jmxUser=null, jmxPassword=null,**

brokers=[BrokerConfig(host=172.23.0.20, port=9092, jmxPort=null, jmxUser=null, jmxPassword=null), 
BrokerConfig(host=172.23.0.21, port=9093, jmxPort=null, jmxUser=null, jmxPassword=null), BrokerConfig(host=172.23.0.22, port=9094, jmxPort=null, jmxUser=null, jmxPassword=null)])})

**All fine but then this? Why does it search in localhost while i changed the ip-address doesn't make any sense. I can't change the IP ** 
`
2021-12-08 15:09:32.081  WARN 1 --- [| adminclient-1] org.apache.kafka.clients.NetworkClient   : [AdminClient clientId=adminclient-1] Connection to node 2 (localhost/127.0.0.1:9094) could not be established. Broker may not be available.

**2021-12-08 15:09:32.084  WARN 1 --- [| adminclient-1] org.apache.kafka.clients.NetworkClient   : [AdminClient clientId=adminclient-1] Connection to node 3 (localhost/127.0.0.1:9096) could not be established. Broker may not be available.**

2021-12-08 15:09:32.086  WARN 1 --- [| adminclient-1] org.apache.kafka.clients.NetworkClient   : [AdminClient clientId=adminclient-1] Connection to node 1 (localhost/127.0.0.1:9092) could not be established. Broker may not be available.
`

**Comment by ynleborg** [comment]
@SENIAN Please check your ports. You have broker on 9092,9093,9093 but in KouncilConfiguration you provided 9092,9094,9096.

**Comment by SENIAN** [comment]
Hi 
Yes the are ports changed now, but got the same issue.
However it has nothing to do with kouncil. Since it uses the kafka.client.NetworkClient service.
So after rubberducking myself on github i've found the issue.
The KAFKA_ADVERTISED_LISTENERS=CLIENT://localhost:9092 , i've changed that to the docker-ip of the broker.
Now he seems to find all brokers and everything works as expected.

Sorry for wasting your time.
