### ISSUE TITLE
Please give instruction on how to run without a docker 

### ISSUE THREAD

**Issue by anildes** [Consdata/kouncil#244]

**Comment by matty-matt** [comment]
Hi, to run kouncil without docker simply follow this instruction: https://docs.kouncil.io/getting-started/development#running-the-project. You should build your project using maven first.

**Comment by anildes** [comment]
Thanks  so mvn spring-boot:run -Dspring-boot.run.arguments="bootstrapServers=localhost:9092" should work for me unless otherwise
