### ISSUE TITLE
Kouncil UI doesn't display topic menu

### ISSUE THREAD

**Issue by jpeace08** [Consdata/kouncil#338]
How can i enable topic menu for UI?
![Screenshot from 2024-03-04 15-54-34](https://github.com/Consdata/kouncil/assets/58292695/3a6f1806-52c9-4b79-9ecc-83a48fa65ccc)

**Comment by hb-0** [comment]
+1

**Comment by jpeace08** [comment]
UPDATE:
I try to access to uri: /topics but get error access denied. My username and password is default.
![Screenshot from 2024-03-05 08-44-19](https://github.com/Consdata/kouncil/assets/58292695/48e489ee-5f0c-488c-abd3-7d9b470f4e18)

**Comment by jpeace08** [comment]
UPDATE
my fault, the credential is define in path */config/security/inmemory/InMemoryConst.java with default option
